### ISSUE TITLE
Infura Project Id Issue

### ISSUE THREAD

**Issue by Sam44323** [Haruxe/NFTFetcher#3]
API call error with infura project id @Haruxe 

<img width="717" alt="Screenshot 2022-10-11 at 12 48 26 PM" src="https://user-images.githubusercontent.com/65643151/195021445-3d1c941e-3b51-44b9-a4b8-740ad32ff4b6.png">

**Comment by haruxe** [comment]
I'm looking into it, has to do with a fix i pushed 😥 thanks

**Comment by haruxe** [comment]
[Fixed!](https://github.com/Haruxe/WalletWrapped/commit/973a42838b7b56372b42b916074b44a6902e3cb1)
